version: "3.3"

volumes:
  postgres-db:

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=fastapi
    
    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      # this is bind mount to synchronize docker app files with my local app files
      - ./:/usr/src/app:ro
    command: ["sh", "-c", "alembic upgrade head &&
                           uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

    #env_file:
    #  - ./.env
    environment:
      # connect to local or server installed postgres db
      #- DATABASE_HOSTNAME=localhost
      #- DATABASE_PORT=5432
      #- DATABASE_PASSWORD=1234
      #- DATABASE_NAME=social_media_fastapi
      #- DATABASE_USERNAME=postgres

      # connect to docker compose service db
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password1234
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres

      - SECRET_KEY=9b68c9f53ff13f75b890b62af1d9435d65827796d21ceb16c5fe431f054dcde3
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
