version: "3.3"

volumes:
  postgres-db:

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    
    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    image: dotpep/social-media-fastapi
    depends_on:
      - db
    ports:
      - 80:8000
    command: ["sh", "-c", "alembic upgrade head &&
                           gunicorn --workers 2 --worker-class uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000"]
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}

      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
