name: Build and Deploy Code

on: [push, pull_request]

jobs:
  my_first_job:
   runs-on: ubuntu-20.04
   steps:
    - name: pulling git repo
      uses: actions/checkout@v2
    - name: say hi to user
      run: echo "hello user!"
